### PR TITLE
Added gitignore

### PR DESCRIPTION
**Pull request by anitamegarry**

### CODE REVIEW

**Comment by Fahi28** [comment]
looks good.

**Review by bentrzcinski — APPROVED** [review]

**Review by jiuliangut — COMMENTED** [review]
nice - could we also add venv and maybe *.csv so we don't push any data?

**Comment by anitamegarry** [comment]
> nice - could we also add venv and maybe *.csv so we don't push any data?

Added!

**Review by jiuliangut — APPROVED** [review]
looks good!

**Pull request merged**
