### PR TITLE
Cleaning up and finishing ETL dockerfile

### PR DESCRIPTION
**Pull request by bentrzcinski**
Small tweaks to the code for improved quality of life, like adding a README.md, and small changes to the dockerfile to finalise it for dockerising the ETL script.

### CODE REVIEW

**Comment by anitamegarry** [comment]
@bentrzcinski could you pull from main?

**Review by jiuliangut — APPROVED** [review]
looks good :)

**Comment by anitamegarry** [comment]
Nice

**Review by anitamegarry — APPROVED** [review]
Nice!

**Pull request merged**
